function package=read_bilingual_package_json(pathValue)
%READ_BILINGUAL_PACKAGE_JSON 读取带“英文（中文）”字段名的数据包JSON。
% 输入:
%   pathValue - package.json文件路径。
% 输出:
%   package   - 恢复为内部英文键名的结构体。

text=fileread(pathValue);
englishKeys={'version','encryption','embedding','additionalCompression', ...
    'carrierSource','carrierSha256','patientInfoSha256','cipherSha256', ...
    'originalHeight','originalWidth','paddedHeight','paddedWidth','nonceHex', ...
    'markedSha512','keyDerivation','firstLambda','codebook','usableCapacityBits', ...
    'payloadBits','blockRows','blockColumns','method','originalLength', ...
    'differentialLength','signByteCount','codeCount','originalSha256', ...
    'compressedLength','dataset','modality','datasetRoot','datasetJson', ...
    'trainingIndex','imageRelativePath','labelRelativePath','imaskRelativePath', ...
    'originalChannels','carrierHeight','carrierWidth','sourceImageSha256'};
chineseKeys={'版本','加密信息','嵌入信息','附加信息压缩', ...
    '载体来源','载体SHA256','患者信息SHA256','密文SHA256', ...
    '原始高度','原始宽度','填充高度','填充宽度','随机数Nonce', ...
    '标记图像SHA512','密钥派生方式','首块Lambda','哈夫曼码本','可用容量比特数', ...
    '嵌入负载比特数','块行数','块列数','压缩方法','原始长度', ...
    '差分流长度','符号字节数','LZW码字数','原始信息SHA256', ...
    '压缩长度','数据集','模态','数据集根目录','数据集描述文件', ...
    '训练索引','图像相对路径','标签相对路径','掩码相对路径', ...
    '原始通道数','载体高度','载体宽度','源图像SHA256'};
for index=1:numel(englishKeys)
    text=strrep(text,['"',englishKeys{index},'（',chineseKeys{index},'）"'], ...
        ['"',englishKeys{index},'"']);
end
package=jsondecode(text);
end
