function [isValid,detail,package]=verify_package(cipherPath,metadataPath, ...
    logoPath,verificationRecordInput,receiverRequestInput,verifierPublicKeyPath)
%VERIFY_PACKAGE 按验证流程算法5和图6执行验证方多级验证。
% 输入:
%   cipherPath              - 验证方收到的密文图像路径。
%   metadataPath            - 当前算法JSON数据包路径。
%   logoPath                - 发送方提供的验证Logo路径。
%   verificationRecordInput - 发送方正确参数结构体或JSON路径。
%   receiverRequestInput    - 接收方提交参数结构体或JSON路径。
%   verifierPublicKeyPath   - 接收端预先信任的验证方X.509公钥路径。
% 输出:
%   isValid - 所有验证条件均通过时为true。
%   detail  - 密文绑定、Logo重算和接收方参数的逐项结果。
%   package - 读取的算法数据包；验证方无需算法口令。

isValid=false;
package=struct();
detail=empty_verification_detail();
try
    package=read_bilingual_package_json(metadataPath);
    record=load_json_or_struct(verificationRecordInput);
    request=load_json_or_struct(receiverRequestInput);
    validate_binding_schema(package,record);
    trustedFingerprint=verification_public_key_fingerprint(verifierPublicKeyPath);
    publicKeyFingerprintValid=strcmpi(trustedFingerprint, ...
        char(record.verifierPublicKeySha256));
    signatureAlgorithmValid=strcmp(char(record.signatureAlgorithm),'SHA256withRSA');
    challenge=hex_to_bytes(char(record.challengeHex));
    challengeSignature=hex_to_bytes(char(record.challengeSignatureHex));
    challengeSignatureValid=verification_verify_challenge( ...
        challenge,challengeSignature,verifierPublicKeyPath);
    actualRecordDigest=verification_record_digest(record);
    signedRecordDigestValid=strcmpi(bytes_to_hex(actualRecordDigest), ...
        char(record.signedRecordSha256));
    recordSignature=hex_to_bytes(char(record.recordSignatureHex));
    recordSignatureValid=verification_verify_challenge( ...
        actualRecordDigest,recordSignature,verifierPublicKeyPath);
    cipher=imread(cipherPath);
    actualCipherHash=bytes_to_hex(sha_bytes(array_to_bytes(cipher),'SHA-256'));
    cipherHashValid=strcmpi(actualCipherHash,char(package.cipherSha256)) && ...
        strcmpi(actualCipherHash,char(record.cipherSha256));
    patientBindingValid=strcmpi(char(record.patientInfoSha256),char(package.patientInfoSha256));
    [~,name,extension]=fileparts(cipherPath);
    cipherNameValid=strcmp(char(record.cipherFileName),[name,extension]);
    challengeStatusValid=strcmp(char(record.challengeStatus),'R_EQUALS_r');

    logoAnalysis=verification_analyze_logo(logoPath,double(record.additionalIndices));
    logoFileHashValid=strcmpi(logoAnalysis.logoSha256,char(record.logoSha256));
    logoFileCharactersValid=strcmp(logoAnalysis.result,char(record.result));
    logoFileProportionValid=abs(logoAnalysis.proportionText-double(record.proportionText))<=1e-12;
    logoFileAdditionalValid=verification_verify_receiver_request(record, ...
        verification_build_receiver_request(logoPath,double(record.additionalIndices)));
    [receiverValid,receiverDetail]=verification_verify_receiver_request(record,request);

    isValid=cipherHashValid && patientBindingValid && cipherNameValid && ...
        challengeStatusValid && publicKeyFingerprintValid && signatureAlgorithmValid && ...
        challengeSignatureValid && signedRecordDigestValid && recordSignatureValid && ...
        logoFileHashValid && logoFileCharactersValid && ...
        logoFileProportionValid && logoFileAdditionalValid && receiverValid;
    detail=struct('cipherHashValid',cipherHashValid, ...
        'patientBindingValid',patientBindingValid,'cipherNameValid',cipherNameValid, ...
        'challengeStatusValid',challengeStatusValid, ...
        'publicKeyFingerprintValid',publicKeyFingerprintValid, ...
        'signatureAlgorithmValid',signatureAlgorithmValid, ...
        'challengeSignatureValid',challengeSignatureValid, ...
        'signedRecordDigestValid',signedRecordDigestValid, ...
        'recordSignatureValid',recordSignatureValid, ...
        'logoFileHashValid',logoFileHashValid, ...
        'logoFileCharactersValid',logoFileCharactersValid, ...
        'logoFileProportionValid',logoFileProportionValid, ...
        'logoFileAdditionalValid',logoFileAdditionalValid, ...
        'receiver',receiverDetail,'isValid',isValid, ...
        'errorIdentifier','','errorMessage','');
catch exception
    detail.errorIdentifier=char(exception.identifier);
    detail.errorMessage=char(exception.message);
end
end

function validate_binding_schema(package,record)
if ~isstruct(package) || ~isscalar(package) || ~isstruct(record) || ~isscalar(record)
    error('Verification:InvalidVerificationSchema','数据包和验证记录必须是标量结构体。');
end
packageFields={'cipherSha256','patientInfoSha256'};
recordFields={'version','result','proportionText','logoSha256', ...
    'additionalIndices','additionalCharacters','cipherFileName','cipherSha256', ...
    'patientInfoSha256','challengeHex','challengeSignatureHex','challengeStatus', ...
    'verifierPublicKeySha256','signatureAlgorithm','signedRecordSha256', ...
    'recordSignatureHex'};
if ~all(isfield(package,packageFields)) || ~all(isfield(record,recordFields))
    error('Verification:MissingVerificationField','数据包或验证记录缺少必需字段。');
end
hashValues={package.cipherSha256,package.patientInfoSha256,record.cipherSha256, ...
    record.patientInfoSha256,record.logoSha256,record.verifierPublicKeySha256, ...
    record.signedRecordSha256};
for k=1:numel(hashValues)
    value=hashValues{k};
    validType=(ischar(value) && isrow(value)) || (isstring(value) && isscalar(value));
    if ~validType || isempty(regexp(char(value),'^[0-9A-Fa-f]{64}$','once'))
        error('Verification:InvalidHash','SHA-256字段必须是64位十六进制字符串。');
    end
end
validate_hex_length(record.challengeHex,64,'challengeHex');
validate_hex_length(record.challengeSignatureHex,768,'challengeSignatureHex');
validate_hex_length(record.recordSignatureHex,768,'recordSignatureHex');
end

function validate_hex_length(value,expectedLength,fieldName)
validType=(ischar(value) && isrow(value)) || (isstring(value) && isscalar(value));
if ~validType || isempty(regexp(char(value), ...
        sprintf('^[0-9A-Fa-f]{%d}$',expectedLength),'once'))
    error('Verification:InvalidSignatureField', ...
        '字段%s必须是%d位十六进制字符串。',fieldName,expectedLength);
end
end

function detail=empty_verification_detail()
receiver=struct('versionValid',false,'charactersValid',false, ...
    'proportionValid',false,'proportionError',NaN,'logoHashValid',false, ...
    'indicesValid',false,'additionalHashValid',false,'isValid',false, ...
    'errorIdentifier','','errorMessage','');
detail=struct('cipherHashValid',false,'patientBindingValid',false, ...
    'cipherNameValid',false,'challengeStatusValid',false, ...
    'publicKeyFingerprintValid',false,'signatureAlgorithmValid',false, ...
    'challengeSignatureValid',false,'signedRecordDigestValid',false, ...
    'recordSignatureValid',false, ...
    'logoFileHashValid',false,'logoFileCharactersValid',false, ...
    'logoFileProportionValid',false,'logoFileAdditionalValid',false, ...
    'receiver',receiver,'isValid',false,'errorIdentifier','','errorMessage','');
end

function value=load_json_or_struct(inputValue)
if isstruct(inputValue), value=inputValue; return; end
pathValue=char(inputValue);
if ~isfile(pathValue), error('Verification:RecordNotFound','验证记录不存在：%s',pathValue); end
value=jsondecode(fileread(pathValue));
end
