function record=verification_build_verification_record(analysis,challenge,signature, ...
    cipherPath,cipherSha256,patientInfoSha256,challengeMetadata)
%VERIFICATION_BUILD_VERIFICATION_RECORD 构建发送方提供的验证流程正确验证参数。
% 输入:
%   analysis          - verification_analyze_logo输出。
%   challenge         - Salomon挑战值r。
%   signature         - 验证方对r的RSA签名。
%   cipherPath        - 当前会话密文路径，仅记录文件名。
%   cipherSha256      - 当前密文SHA-256，用于防止会话串用。
%   patientInfoSha256 - 患者附加信息SHA-256。
%   challengeMetadata - 可选挑战派生元数据。
% 输出:
%   record            - 发送方正确参数结构体。

if nargin<7, challengeMetadata=struct(); end
[~,name,extension]=fileparts(cipherPath);
record=struct('version','verification-v2', ...
    'result',char(analysis.result), ...
    'proportionText',double(analysis.proportionText), ...
    'logoSha256',char(analysis.logoSha256), ...
    'additionalIndices',double(analysis.additionalIndices), ...
    'additionalCharacters',analysis.additionalCharacters, ...
    'challengeHex',bytes_to_hex(uint8(challenge)), ...
    'challengeSignatureHex',bytes_to_hex(uint8(signature)), ...
    'cipherFileName',[name,extension], ...
    'cipherSha256',lower(char(cipherSha256)), ...
    'patientInfoSha256',lower(char(patientInfoSha256)), ...
    'challengeStatus','R_EQUALS_r');
if isfield(challengeMetadata,'nonceHex')
    record.challengeNonceHex=char(challengeMetadata.nonceHex);
end
if isfield(challengeMetadata,'keyDerivation')
    record.challengeKeyDerivation=char(challengeMetadata.keyDerivation);
end
end
