function digest=verification_record_digest(record)
%VERIFICATION_RECORD_DIGEST 计算验证记录的确定性SHA-256签名摘要。
% 输入:
%   record - 尚未加入recordSignatureHex的verification-v2验证记录。
% 输出:
%   digest - 32字节摘要；覆盖Logo、挑战、密文和患者信息绑定字段。

required={'version','result','proportionText','logoSha256','additionalIndices', ...
    'additionalCharacters','challengeHex','challengeSignatureHex','cipherFileName', ...
    'cipherSha256','patientInfoSha256','challengeStatus','verifierPublicKeySha256', ...
    'signatureAlgorithm'};
if ~isstruct(record) || ~isscalar(record) || ~all(isfield(record,required))
    error('Verification:IncompleteSignedRecord','验证记录缺少签名摘要所需字段。');
end

parts={ ...
    ['version=',char(record.version)], ...
    ['result=',char(record.result)], ...
    ['proportionText=',sprintf('%.17g',double(record.proportionText))], ...
    ['logoSha256=',lower(char(record.logoSha256))], ...
    ['additionalIndices=',join_numbers(double(record.additionalIndices))], ...
    ['additionalCharacters=',join_additional(record.additionalCharacters)], ...
    ['challengeHex=',lower(char(record.challengeHex))], ...
    ['challengeSignatureHex=',lower(char(record.challengeSignatureHex))], ...
    ['cipherFileName=',char(record.cipherFileName)], ...
    ['cipherSha256=',lower(char(record.cipherSha256))], ...
    ['patientInfoSha256=',lower(char(record.patientInfoSha256))], ...
    ['challengeStatus=',char(record.challengeStatus)], ...
    ['verifierPublicKeySha256=',lower(char(record.verifierPublicKeySha256))], ...
    ['signatureAlgorithm=',char(record.signatureAlgorithm)]};
if isfield(record,'challengeNonceHex')
    parts{end+1}=['challengeNonceHex=',lower(char(record.challengeNonceHex))];
end
if isfield(record,'challengeKeyDerivation')
    parts{end+1}=['challengeKeyDerivation=',char(record.challengeKeyDerivation)];
end
canonicalText=strjoin(parts,newline);
digest=sha_bytes(unicode2native(canonicalText,'UTF-8'),'SHA-256');
end

function text=join_numbers(values)
values=values(:).';
text=strjoin(arrayfun(@(value)sprintf('%.17g',value),values,'UniformOutput',false),',');
end

function text=join_additional(values)
values=values(:); parts=cell(numel(values),1);
for index=1:numel(values)
    parts{index}=sprintf('%d:%s',double(values(index).index), ...
        lower(char(values(index).hash)));
end
text=strjoin(parts,';');
end
